---
# event specific variables:
room_fahrplan_name: movie-room
voc_event_acronym: cosin


# Authentification and user management
# For more information have a look into the sshd and ssh_authorised_keys roles
# You probably don't want to modify these parameters unless you are
# cloning our setup or add new users
admins:
  - l3d

users:
  l3d:
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com

sshd_default_allowed_users:
  - toolbox
  - root
  - l3d
  - ansible

sshd_default_allowed_groups:
  - toolbox
  - root
  - l3d
  - ansible

accounts:
  - l3d
  - toolbox

only_allow_ed25519: true

ssh_public_key_store: 'admin_ssh_keys'


# some variables for the voc specific playbooks

obs_user: toolbox
username: toolbox


# Font for the Toolbox
fonts_shared:
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-BlackItalic.ttf'
    dest: 'Exo2-BlackItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Black.ttf'
    dest: 'Exo2-Black.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-BoldItalic.ttf'
    dest: 'Exo2-BoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Bold.ttf'
    dest: 'Exo2-Bold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraBoldItalic.ttf'
    dest: 'Exo2-ExtraBoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraBold.ttf'
    dest: 'Exo2-ExtraBold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraLightItalic.ttf'
    dest: 'Exo2-ExtraLightItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraLight.ttf'
    dest: 'Exo2-ExtraLight.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Italic.ttf'
    dest: 'Exo2-Italic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-LightItalic.ttf'
    dest: 'Exo2-LightItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Light.ttf'
    dest: 'Exo2-Light.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-MediumItalic.ttf'
    dest: 'Exo2-MediumItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Medium.ttf'
    dest: 'Exo2-Medium.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Regular.ttf'
    dest: 'Exo2-Regular.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-SemiBoldItalic.ttf'
    dest: 'Exo2-SemiBoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-SemiBold.ttf'
    dest: 'Exo2-SemiBold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ThinItalic.ttf'
    dest: 'Exo2-ThinItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Thin.ttf'
    dest: 'Exo2-Thin.ttf'

