---
# event specific variables:
# Please don't forget to change it *bevore* each event!

##  which room is this encoder for
##  (Maybe you want to overwrite this value in the host_vars)
room_fahrplan_name: 'ruum42'

##  on which event are you
voc_event_acronym: 'tdott'

##  do we want to stream HD
enable_hd_stream: true

##  do we want to stream SD
enable_sd_stream: false

##  where are we streaming to?
##  please think about using an ansible valut for this value!!!
use_trailer_for_rtmp: true
voc_streaming_endpoint: rtmp://live.ber.c3voc.de:1935/stream/q2

# good values for different playbooks
# optimized for the setup in the toolbox bodensee - https://toolbox-bodensee.de
# Please have a look into the roles for more detailed informations

# good voctomix settings
encodermode: 'hd-voctomix'

# Authentification and user management
# For more information have a look into the sshd and ssh_authorised_keys roles
# You probably don't want to modify these parameters unless you are
# cloning our setup or add new users
admins:
  - raoul
  - l3d

users:
  l3d:
   - l3d@pinkie.l3d.yt
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@business.wingcon.com
   - l3d@backup-rsa.l3d.yt
  toolbox:
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com
   - l3d@backup-rsa.l3d.yt
   - raoul@ccczh
  raoul:
   - raoul@ccczh

sshd_default_allowed_users:
  - toolbox
  - root
  - l3d
  - ansible
  - raoul

sshd_default_allowed_groups:
  - toolbox
  - root
  - l3d
  - ansible
  - raoul

accounts:
  - l3d
  - toolbox
  - raoul

only_allow_ed25519: true
ssh_public_key_store: 'admin_ssh_keys'


# some variables for the self-written voc specific playbooks
obs_user: toolbox
username: toolbox
i3wm_user: toolbox
copy_to_user: toolbox

# Font for the Toolbox
# primarly needed for OBS
# we don't use obs. we just install it, because one person wants it.
fonts_shared:
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-BlackItalic.ttf'
    dest: 'Exo2-BlackItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Black.ttf'
    dest: 'Exo2-Black.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-BoldItalic.ttf'
    dest: 'Exo2-BoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Bold.ttf'
    dest: 'Exo2-Bold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraBoldItalic.ttf'
    dest: 'Exo2-ExtraBoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraBold.ttf'
    dest: 'Exo2-ExtraBold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraLightItalic.ttf'
    dest: 'Exo2-ExtraLightItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraLight.ttf'
    dest: 'Exo2-ExtraLight.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Italic.ttf'
    dest: 'Exo2-Italic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-LightItalic.ttf'
    dest: 'Exo2-LightItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Light.ttf'
    dest: 'Exo2-Light.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-MediumItalic.ttf'
    dest: 'Exo2-MediumItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Medium.ttf'
    dest: 'Exo2-Medium.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Regular.ttf'
    dest: 'Exo2-Regular.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-SemiBoldItalic.ttf'
    dest: 'Exo2-SemiBoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-SemiBold.ttf'
    dest: 'Exo2-SemiBold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ThinItalic.ttf'
    dest: 'Exo2-ThinItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Thin.ttf'
    dest: 'Exo2-Thin.ttf'

# not needed stuff
temporarily_disable_screensaver: false
base_pkg_non_free_firmware: true
base_pkg_contrib: true
