---

# Authentification:
admins:
  - l3d

users:
  l3d:
    - l3d
  toolbox:
    - l3d

obs_user: toolbox

# Font
fonts_shared:
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-BlackItalic.ttf'
    dest: 'Exo2-BlackItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Black.ttf'
    dest: 'Exo2-Black.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-BoldItalic.ttf'
    dest: 'Exo2-BoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Bold.ttf'
    dest: 'Exo2-Bold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraBoldItalic.ttf'
    dest: 'Exo2-ExtraBoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraBold.ttf'
    dest: 'Exo2-ExtraBold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraLightItalic.ttf'
    dest: 'Exo2-ExtraLightItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ExtraLight.ttf'
    dest: 'Exo2-ExtraLight.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Italic.ttf'
    dest: 'Exo2-Italic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-LightItalic.ttf'
    dest: 'Exo2-LightItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Light.ttf'
    dest: 'Exo2-Light.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-MediumItalic.ttf'
    dest: 'Exo2-MediumItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Medium.ttf'
    dest: 'Exo2-Medium.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Regular.ttf'
    dest: 'Exo2-Regular.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-SemiBoldItalic.ttf'
    dest: 'Exo2-SemiBoldItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-SemiBold.ttf'
    dest: 'Exo2-SemiBold.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-ThinItalic.ttf'
    dest: 'Exo2-ThinItalic.ttf'
  - type: 'truetype'
    src: 'files/Exo_2/Exo2-Thin.ttf'
    dest: 'Exo2-Thin.ttf'

