---
- name: install python3
  hosts: all
  gather_facts: false
  become: true
  roles:
    - install_python
  tags:
    - default
  vars:
    - ansible_ssh_user: 'ansible'

- name: Apply basic ssh config on all hosts
  hosts: all
  tags: 
   - auth
   - ssh
   - ssh_authorized_keys
   - ssh-auth
   - sshd
   - config
  roles:
    - ssh_authorized_keys
    - sshd
  vars: 
    - ansible_ssh_user: 'ansible'

- name: Apply common basic config on all hosts
  hosts: all
  tags: 
   - auth
   - base
   - base_packages
   - base-packages
   - packages
   - home_environment
   - config
  roles:
    - home_environment
    - base-packages
    - copy_files
  vars: 
    - ansible_ssh_user: 'ansible'

- name: Install useful tools
  hosts: all
  tags: 
   - base
   - base-special
   - install-git-lfs
   - install-bat
  roles:
    - install-bat
    - install-git-lfs

- name: Install i3wm
  hosts: all
  tags: 
   - base
   - os
   - i3wm
   - i3
   - arandr
   - xrandr
   - randr
   - config
  roles:
    - i3wm
    - xrandr

- name: stay awake
  hosts: all
  tags:
    - sleep
    - awake
    - suspend
    - no_sleep
  roles:
    - no_sleep
 
- name: Install video drivers
  hosts: encoder
  tags: 
   - driver
   - blackmagic
   - base-encoder
   - voc_common
   - graphic
   - config
  roles:
    - voc_common
    - graphic
    - blackmagic

- name: Install debugger
  hosts: encoder
  tags: 
   - debug
   - blackmagic
  roles:
    - decklink-debugger

- name: Install voctomix
  hosts: encoder
  tags: 
   - stream
   - voctomix
   - config
  roles:
    - voctomix

- name: Install obs-studio
  hosts: encoder
  tags: 
   - stream
   - obs
  roles:
    - obs-studio

- name: Install obs-studio setup
  hosts: encoder
  tags: 
   - stream
   - obs-setup
   - config
  roles:
    - toolbox-obs-setup

- name: Install Toolbox font
  hosts: all
  tags: 
   - font
   - fonts
   - obs
  roles:
    - fonts
 
- name: Install crs-tools
  hosts: all
  tags: 
   - crs
   - crs-tools
  roles:
  - crs-tools

- name: install php for voc tracker
  hosts: tracker
  tags:
   - config
   - php
   - tracker
   - track
   - traktor
  roles:
    - php

- name: install common voc_encoders stuff
  hosts: encoder
  tags:
   - voc
   - pipeline
   - voc_encoders
   - encode
   - encoders
   - encoder
   - config
  roles:
   - voc_encoders
   - voc_mixer

- name: install voc tracker
  hosts: tracker
  tags:
   - voc
   - config
   - pipeline
   - tracker
   - track
   - traktor
  roles:
    - voc_tracker
