---

- name: Apply basic ssh config on all hosts
  hosts: decoder
  tags: 
   - auth
   - ssh
   - ssh_authorized_keys
   - ssh-auth
   - sshd
  roles:
    - ssh_authorized_keys
    - sshd
  vars: 
    - ansible_ssh_user: 'ansible'

- name: Apply common basic config on all hosts
  hosts: decoder
  tags: 
   - auth
   - base
   - base_packages
   - home_environment
  roles:
    - home_environment
    - base_packages
  vars: 
    - ansible_ssh_user: 'ansible'

- name: Install useful tools
  hosts: decoder
  tags: 
   - base
   - base-special
   - install-git-lfs
   - install-bat
  roles:
    - install-bat
    - install-git-lfs
 
- name: Install video drivers
  hosts: decoder
  tags: 
   - driver
   - blackmagic
   - base-decoder
   - voc_common
   - graphic
  roles:
    - voc_common
    - graphic
    - blackmagic

- name: Install debugger
  hosts: decoder
  tags: 
   - debug
   - blackmagic
  roles:
    - decklink-debugger

- name: Install voctomix
  hosts: decoder
  tags: 
   - stream
   - voctomix
  roles:
    - voctomix

- name: Install obs-studio
  hosts: decoder
  tags: 
   - stream
   - obs
  roles:
    - obs-studio

- name: Install obs-studio setup
  hosts: decoder
  tags: 
   - stream
   - obs-setup
  roles:
    - toolbox-obs-setup

- name: Install Toolbox font
  hosts: decoder
  tags: 
   - font
   - fonts
   - obs
  roles:
    - fonts
 
- name: Install crs-tools
  hosts: decoder
  tags: 
   - crs
   - crs-tools
  roles:
  - crs-tools


