---

- name: Apply common basic config on all hosts
  hosts: voc
  tags: 
   - auth
   - base
  roles:
    - home_environment
    - base_packages
  vars: 
    - ansible_ssh_user: 'root'

- name: Apply basic ssh config on all hosts
  hosts: voc
  tags: 
   - auth
   - ssh
  roles:
    - ssh_authorized_keys
    - sshd
  vars: 
    - ansible_ssh_user: 'root'

- name: Install video drivers
  hosts: voc
  tags: 
   - driver
   - blackmagic
  roles:
    - graphic
    - blackmagic

- name: Install debugger
  hosts: voc
  tags: 
   - debug
   - blackmagic
  roles:
    - decklink-debugger


