---

- name: Apply common basic config on all hosts
  hosts: voc
  tags: auth
  roles:
    - ssh_authorized_keys
    - home_environment
    - base_packages
    - sshd
  vars: 
    - ansible_ssh_user: 'root'


