
# Because Git-LFS repository use HTTPS, apt-transport-https package is necessary.
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Add Git-LFS repository key
  apt_key:
    url: https://packagecloud.io/github/git-lfs/gpgkey
    state: present

- name: Add Git-LFS repository source
  get_url:
    url: https://packagecloud.io/install/repositories/github/git-lfs/config_file.list?os=debian&dist={{ansible_distribution_major_version}}&source=script
    dest: /etc/apt/sources.list.d/github_git-lfs.list
    owner: root
    group: root
    mode: 0644

- name: Add git-lfs package
  apt: 
    name: git-lfs
    state: latest 
    update_cache: yes

