
- name: Add Git-LFS repository source
  get_url:
    url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh 
    dest: /opt/github_git-lfs.sh
    owner: root
    group: root
    mode: 0755
  register: script

- name: Add Git-LFS repository source
  shell: /opt/github_git-lfs.sh
  when: script.changed
  become: yes

