---

- name: create toolbox obs config directory
  file:
    path: /home/{{ obs_user }}/.config
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"  
- file:
    path: /home/{{ obs_user }}/.config/obs-studio
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}" 
- file:
    path: /home/{{ obs_user }}/.config/obs-studio/basic
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"

- name: clone obs toolbox config
  git:
    repo: https://github.com/ToolboxBodensee/obs-config.git  
    dest: /home/{{ obs_user }}/.config/obs-studio/basic
    update: yes
    clone: yes
    force: yes

- file:
    path: /home/{{ obs_user }}/.config/obs-studio/basic
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
    recurse: true

- name: create toolbox obs data directory
  file:
    path: /srv/stream
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"  
- file:
    path: /srv/stream/toolbox
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"

- file:
    path: /srv/stream/toolbox/streamassets
    state: directory
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
    recurse: yes

- name: clone obs toolbox media
  git:
    repo: https://github.com/ToolboxBodensee/streamassets.git
    dest: /srv/stream/toolbox/streamassets
    update: yes
    clone: yes
    force: yes

- name: git lfs pull toolbox media
  command: git lfs pull
  args:
    chdir: /srv/stream/toolbox/streamassets



