---
- name: create toolbox obs config directory
  file:
    path: /home/{{ obs_user }}/.config
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"  
  become: true
- file:
    path: /home/{{ obs_user }}/.config/obs-studio
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}" 
  become: true
- file:
    path: /home/{{ obs_user }}/.config/obs-studio/basic
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
  become: true

- name: clone obs toolbox config
  become: true
  git:
    repo: https://github.com/ToolboxBodensee/obs-config.git
    dest: /home/{{ obs_user }}/.config/obs-studio/basic
    update: yes
    clone: yes
    force: yes

- file:
    path: /home/{{ obs_user }}/.config/obs-studio/basic
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
    recurse: true
  become: true

- name: create toolbox obs data directory
  file:
    path: /srv/stream
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
  become: true
- file:
    path: /srv/stream/toolbox
    state: directory
    mode: 0755
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
  become: true

- name: create sreamassets dir
  become: true
  file:
    path: /srv/stream/toolbox/streamassets
    state: directory
    owner: "{{ obs_user }}"
    group: "{{ obs_user }}"
    recurse: yes

- name: clone obs toolbox media
  become: true
  git:
    repo: https://github.com/ToolboxBodensee/streamassets.git
    dest: /srv/stream/toolbox/streamassets
    update: yes
    clone: yes
    force: yes
    version: master

