    - name: check for python3
      stat:
        path: /usr/bin/python3
      ignore_errors: yes
      register: systempython
      changed_when: false

    - name: install python for debian based systems
      raw: apt-get -y install python3-simplejson
      ignore_errors: yes
      register: result
      when: systempython.stat is undefined or not systempython.stat.exists
      until: result is succeeded

    - name: check for python2
      stat:
        path: /usr/bin/python2
      ignore_errors: yes
      register: systempython2
      changed_when: false
      when: not result is succeeded

    - name: prepare for python3 on centos systems
      raw: yum -y groupinstall development
      ignore_errors: yes
      register: rhel_result
      when: 
        - systempython2.stat is undefined or not systempython2.stat.exists
        - systempython.stat is undefined  or  not systempython.stat.exists
      until: rhel_result is succeeded

    - name: install python3 sources for centos systems
      raw: yum -y install https://centos7.iuscommunity.org/ius-release.rpm
      ignore_errors: yes
      register: result
      when: 
        - systempython2.stat is undefined or not systempython2.stat.exists
        - systempython.stat is undefined  or  not systempython.stat.exists
        - rhel_result is succeeded
      until: result is succeeded

    - name: install python3 for centos systems
      raw: yum -y install python36.x86_64
      ignore_errors: yes
      register: result
      when: 
        - systempython2.stat is undefined or not systempython2.stat.exists
        - systempython.stat is undefined  or  not systempython.stat.exists
        - rhel_result is succeeded
      until: result is succeeded

    - name: install python2 for centos systems
      raw: yum -y install python.x86_64
      ignore_errors: yes
      register: result
      when: 
        - systempython2.stat is undefined or not systempython2.stat.exists
        - systempython.stat is undefined  or  not systempython.stat.exists
        - rhel_result is succeeded
      until: result is succeeded

    - name: install python2 for centos systems
      raw: yum -y install libselinux-python.x86_64
      ignore_errors: yes
      register: result
      when: 
        - systempython2.stat is undefined or not systempython2.stat.exists
        - systempython.stat is undefined  or  not systempython.stat.exists
        - rhel_result is succeeded
      until: result is succeeded




    - name: Collect only facts returned by facter
      setup:
        gather_subset:
          - 'all'

    - debug:
        msg: "Operating System: {{ ansible_os_family }}"

    - debug:
        var: hostvars[inventory_hostname]
        verbosity: 4

