---
# do we have a nvidia gpu?
nvidia_gpu: false

# where are blackmagic drivers located?
blackmagic:
  urls:
    desktopvideo: https://releases.tbbs.me/download/desktopvideo_10.11.4a9_amd64.deb
    desktopvideo_gui: https://releases.tbbs.me/download/desktopvideo-gui_10.11.4a9_amd64.deb
    desktopvideo_scanner: https://releases.tbbs.me/download/desktopvideo-scanner_10.11.4a9_amd64.deb
    mediaexpress: https://releases.tbbs.me/download/mediaexpress_3.5.7a5_amd64.deb
  dkms_version: 10.1.4a9

  sdk: https://releases.tbbs.me/download/Blackmagic_DeckLink_SDK_10.11.4.zip 
  sdk_number: "10.11.4"
# blackmagic card
blackmagic_sources:
 - card: 0
   connection: SDI
   audio: true
#   mode: 18  # optional


i3_monitors:
  - monitor:
    id: 1
    output: "HDMI-0"
    mode: "1920x1200"
    pos: "0x0"
    rotate: "normal"
    workspaces: [1,2,3,4,5,6,7,8,9]
  - monitor:
    id: 2
    output: "DVI-1"
    mode: "1280x1024"
    pos: "1920x0"
    rotate: "left"
    workspaces: [0]
