---
- name: Disbale IPv6 on all interfaces
  become: true
  when: disable_ipv6 | bool
  sysctl: 
    name: 'net.ipv6.conf.all.disable_ipv6'
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
